2022-09-03 13:23:54,719 ERROR frappe Could not take error snapshot: name 'six' is not defined
Site: dcode.com
Form Dict: {'cmd': 'frappe.core.page.background_jobs.background_jobs.get_scheduler_status'}
Traceback (most recent call last):
  File "/home/snehal/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "/home/snehal/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/snehal/frappe-bench/apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "/home/snehal/frappe-bench/apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/snehal/frappe-bench/apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "/home/snehal/frappe-bench/apps/frappe/frappe/core/page/background_jobs/background_jobs.py", line 85, in get_scheduler_status
    return [_("Inactive"), "red"]
  File "/home/snehal/frappe-bench/apps/frappe/frappe/__init__.py", line 115, in _
    translated_string = get_full_dict(lang).get(msg)
  File "/home/snehal/frappe-bench/apps/frappe/frappe/translate.py", line 279, in get_full_dict
    frappe.local.lang_full_dict = load_lang(lang)
  File "/home/snehal/frappe-bench/apps/frappe/frappe/translate.py", line 303, in load_lang
    path = os.path.join(frappe.get_pymodule_path(app), "translations", lang + ".csv")
  File "/home/snehal/frappe-bench/apps/frappe/frappe/__init__.py", line 1244, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/snehal/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snehal/frappe-bench/apps/frappe/frappe/utils/error.py", line 49, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/snehal/frappe-bench/apps/frappe/frappe/utils/error.py", line 66, in get_snapshot
    if isinstance(etype, six.class_types):
NameError: name 'six' is not defined
